# Generated by Django 2.2.3 on 2019-07-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='标题')),
                ('my_title', models.CharField(max_length=256, null=True, verbose_name='我的标题')),
            ],
        ),
        migrations.CreateModel(
            name='UsrSpeedPecpt',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rounds', models.CharField(blank=True, db_column='ROUNDS', max_length=4, null=True)),
                ('sdate', models.CharField(blank=True, db_column='SDATE', max_length=255, null=True)),
                ('msisdn', models.CharField(db_column='MSISDN', max_length=255)),
                ('dl_speed', models.FloatField(blank=True, db_column='DL_SPEED', null=True)),
                ('bp_dl_speed', models.FloatField(blank=True, db_column='BP_DL_SPEED', null=True)),
                ('bp_dl_data', models.FloatField(blank=True, db_column='BP_DL_DATA', null=True)),
                ('bp_dl_dura', models.FloatField(blank=True, db_column='BP_DL_DURA', null=True)),
                ('ul_speed', models.FloatField(blank=True, db_column='UL_SPEED', null=True)),
                ('bp_ul_speed', models.FloatField(blank=True, db_column='BP_UL_SPEED', null=True)),
                ('sp_dl_delay', models.FloatField(blank=True, db_column='SP_DL_DELAY', null=True)),
                ('sp_ul_delay', models.FloatField(blank=True, db_column='SP_UL_DELAY', null=True)),
            ],
            options={
                'db_table': 'Usr_Speed_Pecpt',
                'managed': True,
            },
        ),
    ]
